#!/bin/bash

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
frontend web
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    option http-server-close
    server 418619-web-01 54.227.201.4:80 check
    server 418619-web-02 34.207.121.32:80 check
EOF

# Restart HAProxy to apply the changes
sudo service haproxy restart

# Ensure HAProxy is managed via an init script
sudo systemctl enable haproxy
